# Generated by Django 5.2.5 on 2025-08-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
                ('completed_name', models.TextField()),
                ('common_name', models.TextField()),
                ('capital', models.CharField(blank=True, max_length=255)),
                ('continent', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
