# Generated by Django 5.2.5 on 2025-08-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countriesmodel',
            old_name='common_name',
            new_name='sovereignty',
        ),
    ]
